name: Build

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Build Docker image
    strategy:
      matrix:
        platform: [ linux/amd64, linux/arm64 ]
    runs-on: ubuntu-20.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u opendexbot --password-stdin
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: |
          scripts/build -p ${{ matrix.platform }}
          scripts/build -p ${{ matrix.platform }} -r ghcr.io
